# Generated by Django 6.0.1 on 2026-01-25 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CancerRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("features", models.TextField()),
                ("prediction", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiabetesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("pregnancies", models.IntegerField()),
                ("glucose", models.FloatField()),
                ("blood_pressure", models.FloatField()),
                ("skin_thickness", models.FloatField()),
                ("insulin", models.FloatField()),
                ("bmi", models.FloatField()),
                ("diabetes_pedigree_function", models.FloatField()),
                ("age", models.IntegerField()),
                ("prediction", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeartRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("chest_pain_type", models.CharField(max_length=50)),
                ("resting_bp", models.FloatField()),
                ("cholesterol", models.FloatField()),
                ("fasting_bs", models.CharField(max_length=10)),
                ("resting_ecg", models.CharField(max_length=50)),
                ("max_hr", models.FloatField()),
                ("exercise_angina", models.CharField(max_length=10)),
                ("old_peak", models.FloatField()),
                ("st_slope", models.CharField(max_length=50)),
                ("prediction", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagePredictionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("disease_type", models.CharField(max_length=50)),
                ("image_path", models.CharField(max_length=500)),
                ("prediction", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiverRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("total_bilirubin", models.FloatField()),
                ("direct_bilirubin", models.FloatField()),
                ("alkaline_phosphatase", models.FloatField()),
                ("alamine_aminotransferase", models.FloatField()),
                ("aspartate_aminotransferase", models.FloatField()),
                ("total_proteins", models.FloatField()),
                ("albumin", models.FloatField()),
                ("albumin_and_globulin_ratio", models.FloatField()),
                ("prediction", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
